export const MEMES_LIST_REQUEST = "MEMES_LIST_REQUEST";
export const MEMES_LIST_SUCCESS = "MEMES_LIST_SUCCESS";
export const MEMES_LIST_FAIL = "MEMES_LIST_FAIL";
export const DELETE_MEMES = "DELETE_MEMES";
export const DELETE_MEMES_FAIL = "DELETE_MEMES_FAIL";
export const CREATE_MEMES = "CREATE_MEMES";
export const CREATE_MEMES_FAIL = "CREATE_MEMES_FAIL";
